hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user enable --now waybar.service")
    hl.exec_cmd("systemctl --user enable --now hyprpolkitagent")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Rosepine-Dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
end)
