local function toggle_workspace_floating()
    local workspace = hl.get_active_workspace()
    if not workspace then
        return
    end
    local windows = hl.get_workspace_windows(workspace)
    local all_floating = true
    for _, window in ipairs(windows) do
        if not window.floating then
            all_floating = false
            break
        end
    end
    for _, window in ipairs(windows) do
        hl.dispatch(hl.dsp.window.float({ window = window, action = all_floating and "disable" or "enable" }))
    end
end

hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("uwsm app -- kitty"), { description = "Open the terminal" })
hl.bind("SUPER + B", hl.dsp.exec_cmd("~/.config/hypr/scripts/launch-or-focus.py firefox"), { description = "Open or focus the browser" })
hl.bind("SUPER + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/launch-or-focus.py dolphin"), { description = "Open or focus the filemanager" })
hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Kill active window" })
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd("hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill"), { description = "Quit active window and all open instances" })
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }), { description = "Set active window to fullscreen" })
hl.bind("SUPER + M", hl.dsp.window.fullscreen({ mode = "maximized" }), { description = "Maximize Window" })
hl.bind("SUPER + T", hl.dsp.window.float(), { description = "Toggle active windows into floating mode" })
hl.bind("SUPER + SHIFT + T", toggle_workspace_floating, { description = "Toggle all windows into floating mode" })
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }), { description = "Move focus left" })
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }), { description = "Move focus right" })
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }), { description = "Move focus up" })
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }), { description = "Move focus down" })
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { description = "Move window with the mouse", mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { description = "Resize window with the mouse", mouse = true })
hl.bind("SUPER + SHIFT + H", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Reduce window width with keyboard" })
hl.bind("SUPER + SHIFT + L", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { description = "Increase window width with keyboard" })
hl.bind("SUPER + SHIFT + K", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { description = "Reduce window height with keyboard" })
hl.bind("SUPER + SHIFT + J", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), { description = "Increase window height with keyboard" })
hl.bind("SUPER + G", hl.dsp.group.toggle(), { description = "Toggle window group" })
hl.bind("SUPER + ALT + H", hl.dsp.window.swap({ direction = "l" }), { description = "Swap tiled window left" })
hl.bind("SUPER + ALT + L", hl.dsp.window.swap({ direction = "r" }), { description = "Swap tiled window right" })
hl.bind("SUPER + ALT + K", hl.dsp.window.swap({ direction = "u" }), { description = "Swap tiled window up" })
hl.bind("SUPER + ALT + J", hl.dsp.window.swap({ direction = "d" }), { description = "Swap tiled window down" })
hl.bind("ALT + Tab", hl.dsp.window.cycle_next(), { description = "Cycle between windows", repeating = true })
hl.bind("ALT + Tab", hl.dsp.window.alter_zorder({ mode = "top" }), { description = "Bring active window to the top", repeating = true })
hl.bind("SUPER + P", hl.dsp.exec_cmd("~/.config/hypr/scripts/cliphist.sh"), { description = "Open clipboard manager" })
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("~/.config/hypr/scripts/package-menu.sh"), { description = "Open package manager" })
hl.bind("SUPER + CTRL + P", hl.dsp.exec_cmd("pavucontrol"), { description = "Open clipboard manager" })
hl.bind("SUPER + A", hl.dsp.exec_cmd("~/.config/hypr/scripts/ai.sh"), { description = "Open AI search engine service in browser" })
hl.bind("SUPER + Y", hl.dsp.exec_cmd("kitty -e youtube-tui"), { description = "Open youtube in terminal" })
hl.bind("SUPER + CTRL + B", hl.dsp.exec_cmd("blueman-manager"), { description = "Open bluetooth manager" })
hl.bind("SUPER + N", hl.dsp.exec_cmd("kitty -e nvim ."), { description = "Open neovim" })
hl.bind("SUPER + CTRL + R", hl.dsp.exec_cmd("hyprctl reload"), { description = "Reload Hyprland configuration" })
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"), { description = "Reload Hyprland configuration" })
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"), { description = "Take a screenshot" })
hl.bind("SUPER + CTRL + Q", hl.dsp.exec_cmd("~/.config/hypr/scripts/wlogout.sh"), { description = "Start wlogout" })
hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd("hyprlock"), { description = "Start wlogout" })
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("waypaper --random"), { description = "Change the wallpaper" })
hl.bind("SUPER + CTRL + W", hl.dsp.exec_cmd("waypaper"), { description = "Open wallpaper selector" })
local launcher = "~/.config/hypr/scripts/launcher.sh"
hl.bind("SUPER + SHIFT + RETURN", hl.dsp.exec_cmd(launcher), { description = "Open application launcher" })
hl.bind("SUPER + CTRL + RETURN", hl.dsp.exec_cmd(launcher), { description = "Open application launcher" })
hl.bind("SUPER + CTRL + K", hl.dsp.exec_cmd("~/.config/hypr/scripts/keybindings.sh"), { description = "Show keybindings" })
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("killall waybar; waybar"), { description = "Reload waybar" })
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }), { description = "Open workspace 1" })
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }), { description = "Open workspace 2" })
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }), { description = "Open workspace 3" })
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }), { description = "Open workspace 4" })
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }), { description = "Open workspace 5" })
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }), { description = "Open workspace 6" })
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }), { description = "Open workspace 7" })
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }), { description = "Open workspace 8" })
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }), { description = "Open workspace 9" })
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }), { description = "Open workspace 10" })
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1", follow = true }), { description = "Move active window to workspace 1" })
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2", follow = true }), { description = "Move active window to workspace 2" })
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3", follow = true }), { description = "Move active window to workspace 3" })
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4", follow = true }), { description = "Move active window to workspace 4" })
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5", follow = true }), { description = "Move active window to workspace 5" })
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6", follow = true }), { description = "Move active window to workspace 6" })
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7", follow = true }), { description = "Move active window to workspace 7" })
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8", follow = true }), { description = "Move active window to workspace 8" })
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9", follow = true }), { description = "Move active window to workspace 9" })
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10", follow = true }), { description = "Move active window to workspace 10" })
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "m+1" }), { description = "Open next workspace" })
hl.bind("SUPER + SHIFT + Tab", hl.dsp.focus({ workspace = "m-1" }), { description = "Open previous workspace" })
hl.bind("SUPER + CTRL + 1", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 1"), { description = "Move all windows to workspace 1" })
hl.bind("SUPER + CTRL + 2", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 2"), { description = "Move all windows to workspace 2" })
hl.bind("SUPER + CTRL + 3", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 3"), { description = "Move all windows to workspace 3" })
hl.bind("SUPER + CTRL + 4", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 4"), { description = "Move all windows to workspace 4" })
hl.bind("SUPER + CTRL + 5", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 5"), { description = "Move all windows to workspace 5" })
hl.bind("SUPER + CTRL + 6", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 6"), { description = "Move all windows to workspace 6" })
hl.bind("SUPER + CTRL + 7", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 7"), { description = "Move all windows to workspace 7" })
hl.bind("SUPER + CTRL + 8", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 8"), { description = "Move all windows to workspace 8" })
hl.bind("SUPER + CTRL + 9", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 9"), { description = "Move all windows to workspace 9" })
hl.bind("SUPER + CTRL + 0", hl.dsp.exec_cmd("~/.config/hypr/scripts/moveTo.sh 10"), { description = "Move all windows to workspace 10" })
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Open next workspace" })
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Open previous workspace" })
hl.bind("SUPER + CTRL + down", hl.dsp.focus({ workspace = "empty" }), { description = "Open the next empty workspace" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -q s +10%"), { description = "Increase brightness by 10%" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -q s 10%-"), { description = "Reduce brightness by 10%" })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ +5%"), { description = "Increase volume by 5%" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0 && pactl set-sink-volume @DEFAULT_SINK@ -5%"), { description = "Reduce volume by 5%" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"), { description = "Toggle mute" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { description = "Audio play pause" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"), { description = "Audio pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { description = "Audio next" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { description = "Audio previous" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"), { description = "Toggle microphone" })
hl.bind("XF86ScreenSaver", hl.dsp.exec_cmd("hyprlock"), { description = "Open screenlock" })
hl.bind("code:238", hl.dsp.exec_cmd("brightnessctl -d smc::kbd_backlight s +10"))
hl.bind("code:237", hl.dsp.exec_cmd("brightnessctl -d smc::kbd_backlight s 10-"))
