# https://wiki.hypr.land/Configuring/Window-Rules/
# https://deepwiki.com/hyprwm/hyprland-wiki/3.3-window-rules
# hyprctl clients - for info about applications

windowrule = float on, match:class blueman-manager
windowrule = float on, match:class org.kde.dolphin
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = size <50% <50%, match:class org.kde.dolphin
windowrule = size 50% 50%, match:class org.pulseaudio.pavucontrol
windowrule = no_blur on, match:class firefox
windowrule = workspace 2, match:class mpv

# Resolve JetBrains IDEs tooltip flickering
windowrule = no_initial_focus on, match:class (jetbrains-.*)
